/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c WelcomeService -l Welcome -a welcomeservice com.deepin.dde.welcome.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "welcomeservice.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WelcomeService
 */

WelcomeService::WelcomeService(Welcome *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WelcomeService::~WelcomeService()
{
    // destructor
}

void WelcomeService::Exit()
{
    qDebug() << Q_FUNC_INFO;

    // handle method call com.deepin.dde.Welcome.Exit
    parent()->dbus_exit();
}

void WelcomeService::Show()
{
    qDebug() << Q_FUNC_INFO;

    // handle method call com.deepin.dde.Welcome.Show
    parent()->dbus_show();
}

