/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c WelcomeService -l Welcome -a welcomeservice com.deepin.dde.welcome.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WELCOMESERVICE_H
#define WELCOMESERVICE_H

#include "welcome.h"

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.Welcome
 */
class WelcomeService: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.Welcome")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.Welcome\">\n"
"    <method name=\"Show\"/>\n"
"    <method name=\"Exit\"/>\n"
"  </interface>\n"
        "")
public:
    WelcomeService(Welcome *parent);
    virtual ~WelcomeService();

    inline Welcome *parent() const
    { return static_cast<Welcome *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Exit();
    void Show();
Q_SIGNALS: // SIGNALS
};

#endif
