/**
 * Copyright (C) 2015 Deepin Technology Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 **/

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.daemon.InputDevice.Keyboard.xml -c LayoutDbus -p layoutdbus
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef LAYOUTDBUS_H_1446712320
#define LAYOUTDBUS_H_1446712320

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.daemon.InputDevice.Keyboard
 */
class LayoutDbus: public QDBusAbstractInterface
{
    Q_OBJECT

    Q_SLOT void __propertyChanged__(const QDBusMessage& msg)
    {
        QList<QVariant> arguments = msg.arguments();
        if (3 != arguments.count())
            return;
        QString interfaceName = msg.arguments().at(0).toString();
        if (interfaceName !="com.deepin.daemon.InputDevice.Keyboard")
            return;
        QVariantMap changedProps = qdbus_cast<QVariantMap>(arguments.at(1).value<QDBusArgument>());
        foreach(const QString &prop, changedProps.keys()) {
        const QMetaObject* self = metaObject();
            for (int i=self->propertyOffset(); i < self->propertyCount(); ++i) {
                QMetaProperty p = self->property(i);
                if (p.name() == prop) {
 	            Q_EMIT p.notifySignal().invoke(this);
                }
            }
        }
   }
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.daemon.InputDevice.Keyboard"; }

public:
    LayoutDbus(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~LayoutDbus();

    Q_PROPERTY(QString CurrentLayout READ currentLayout WRITE setCurrentLayout NOTIFY CurrentLayoutChanged)
    inline QString currentLayout() const
    { return qvariant_cast< QString >(property("CurrentLayout")); }
    inline void setCurrentLayout(const QString &value)
    { setProperty("CurrentLayout", QVariant::fromValue(value)); }

    Q_PROPERTY(QStringList UserLayoutList READ userLayoutList NOTIFY UserLayoutListChanged)
    inline QStringList userLayoutList() const
    { return qvariant_cast< QStringList >(property("UserLayoutList")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> GetLayoutDesc(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("GetLayoutDesc"), argumentList);
    }

Q_SIGNALS: // SIGNALS
// begin property changed signals
void CurrentLayoutChanged();
void UserLayoutListChanged();
};

namespace com {
  namespace deepin {
    namespace daemon {
      namespace InputDevice {
        typedef ::LayoutDbus Keyboard;
      }
    }
  }
}
#endif
