#!/bin/sh

set -e 

if [ "$1" = "configure" ];then
	update-alternatives --install /usr/share/xgreeters/lightdm-greeter.desktop \
	lightdm-greeter /usr/share/xgreeters/lightdm-deepin-greeter.desktop 90
fi

#DEBHELPER#
exit 0
