#!/bin/sh

dialog_file="/usr/lib/dde-control-center/reset-password-dialog"

#判断文件是否存在
if [ -f "$dialog_file" ]; then
 chown nobody:nogroup $dialog_file
 chmod 500 $dialog_file
else
 echo "error:$dialog_file 文件不存在!"
fi

exit 0