/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-ui/xml/com.deepin.chromeExtension.TabsLimit.xml -a ./dde-session-ui/toolGenerate/qdbusxml2cpp/com.deepin.chromeExtension.TabsLimitAdaptor -i ./dde-session-ui/toolGenerate/qdbusxml2cpp/com.deepin.chromeExtension.TabsLimit.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-ui/toolGenerate/qdbusxml2cpp/com.deepin.chromeExtension.TabsLimitAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TabsLimitAdaptor
 */

TabsLimitAdaptor::TabsLimitAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TabsLimitAdaptor::~TabsLimitAdaptor()
{
    // destructor
}

void TabsLimitAdaptor::CloseTab(int in0)
{
    // handle method call com.deepin.chromeExtension.TabsLimit.CloseTab
    QMetaObject::invokeMethod(parent(), "CloseTab", Q_ARG(int, in0));
}

QString TabsLimitAdaptor::GetProcessInfo()
{
    // handle method call com.deepin.chromeExtension.TabsLimit.GetProcessInfo
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetProcessInfo", Q_RETURN_ARG(QString, out0));
    return out0;
}

void TabsLimitAdaptor::OpenUrl(const QString &in0)
{
    // handle method call com.deepin.chromeExtension.TabsLimit.OpenUrl
    QMetaObject::invokeMethod(parent(), "OpenUrl", Q_ARG(QString, in0));
}

