/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-ui/xml/com.deepin.chromeExtension.TabsLimit.xml -a ./dde-session-ui/toolGenerate/qdbusxml2cpp/com.deepin.chromeExtension.TabsLimitAdaptor -i ./dde-session-ui/toolGenerate/qdbusxml2cpp/com.deepin.chromeExtension.TabsLimit.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_CHROMEEXTENSION_TABSLIMITADAPTOR_H
#define COM_DEEPIN_CHROMEEXTENSION_TABSLIMITADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-ui/toolGenerate/qdbusxml2cpp/com.deepin.chromeExtension.TabsLimit.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.chromeExtension.TabsLimit
 */
class TabsLimitAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.chromeExtension.TabsLimit")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.chromeExtension.TabsLimit\">\n"
"    <method name=\"CloseTab\">\n"
"      <arg direction=\"in\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"GetProcessInfo\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"OpenUrl\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TabsLimitAdaptor(QObject *parent);
    virtual ~TabsLimitAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void CloseTab(int in0);
    QString GetProcessInfo();
    void OpenUrl(const QString &in0);
Q_SIGNALS: // SIGNALS
};

#endif
