/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-ui/xml/org.deepin.dde.ImageBlur1.xml -a ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageBlur1Adaptor -i ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageBlur1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_IMAGEBLUR1ADAPTOR_H
#define ORG_DEEPIN_DDE_IMAGEBLUR1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageBlur1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.ImageBlur1
 */
class ImageBlur1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.ImageBlur1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.ImageBlur1\">\n"
"    <method name=\"Get\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <signal name=\"BlurDone\">\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"b\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ImageBlur1Adaptor(QObject *parent);
    virtual ~ImageBlur1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString Get(const QString &in0);
Q_SIGNALS: // SIGNALS
    void BlurDone(const QString &in0, const QString &in1, bool in2);
};

#endif
