/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-ui/xml/org.deepin.dde.SoundEffect1.xml -a ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.SoundEffect1Adaptor -i ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.SoundEffect1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.SoundEffect1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SoundEffect1Adaptor
 */

SoundEffect1Adaptor::SoundEffect1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SoundEffect1Adaptor::~SoundEffect1Adaptor()
{
    // destructor
}

bool SoundEffect1Adaptor::enabled() const
{
    // get the value of property Enabled
    return qvariant_cast< bool >(parent()->property("Enabled"));
}

void SoundEffect1Adaptor::setEnabled(bool value)
{
    // set the value of property Enabled
    parent()->setProperty("Enabled", QVariant::fromValue(value));
}

void SoundEffect1Adaptor::EnableSound(const QString &name, bool enabled)
{
    // handle method call org.deepin.dde.SoundEffect1.EnableSound
    QMetaObject::invokeMethod(parent(), "EnableSound", Q_ARG(QString, name), Q_ARG(bool, enabled));
}

QMap<QString,bool> SoundEffect1Adaptor::GetSoundEnabledMap()
{
    // handle method call org.deepin.dde.SoundEffect1.GetSoundEnabledMap
    QMap<QString,bool> result;
    QMetaObject::invokeMethod(parent(), "GetSoundEnabledMap", Q_RETURN_ARG(QMap<QString,bool>, result));
    return result;
}

QString SoundEffect1Adaptor::GetSoundFile(const QString &name)
{
    // handle method call org.deepin.dde.SoundEffect1.GetSoundFile
    QString file;
    QMetaObject::invokeMethod(parent(), "GetSoundFile", Q_RETURN_ARG(QString, file), Q_ARG(QString, name));
    return file;
}

QString SoundEffect1Adaptor::GetSystemSoundFile(const QString &name)
{
    // handle method call org.deepin.dde.SoundEffect1.GetSystemSoundFile
    QString file;
    QMetaObject::invokeMethod(parent(), "GetSystemSoundFile", Q_RETURN_ARG(QString, file), Q_ARG(QString, name));
    return file;
}

bool SoundEffect1Adaptor::IsSoundEnabled(const QString &name)
{
    // handle method call org.deepin.dde.SoundEffect1.IsSoundEnabled
    bool enabled;
    QMetaObject::invokeMethod(parent(), "IsSoundEnabled", Q_RETURN_ARG(bool, enabled), Q_ARG(QString, name));
    return enabled;
}

void SoundEffect1Adaptor::PlaySound(const QString &name)
{
    // handle method call org.deepin.dde.SoundEffect1.PlaySound
    QMetaObject::invokeMethod(parent(), "PlaySound", Q_ARG(QString, name));
}

void SoundEffect1Adaptor::PlaySystemSound(const QString &name)
{
    // handle method call org.deepin.dde.SoundEffect1.PlaySystemSound
    QMetaObject::invokeMethod(parent(), "PlaySystemSound", Q_ARG(QString, name));
}

