/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-ui/xml/org.deepin.dde.ImageBlur1.xml -a ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageBlur1Adaptor -i ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageBlur1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-ui/toolGenerate/qdbusxml2cpp/org.deepin.dde.ImageBlur1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ImageBlur1Adaptor
 */

ImageBlur1Adaptor::ImageBlur1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ImageBlur1Adaptor::~ImageBlur1Adaptor()
{
    // destructor
}

QString ImageBlur1Adaptor::Get(const QString &in0)
{
    // handle method call org.deepin.dde.ImageBlur1.Get
    QString out0;
    QMetaObject::invokeMethod(parent(), "Get", Q_RETURN_ARG(QString, out0), Q_ARG(QString, in0));
    return out0;
}

